from os import path
from time import strftime
from calc import relu, sigmoid, tanh

DEBUG = False
DEBUG_FILENAME = (strftime("%m-%d-%Y")) + "_RENDER_QUEUE_CAP_120.prof"
WIDTH, HEIGHT = 1920, 1080
DS_WIDTH, DS_HEIGHT = 576, 320
FPS = 120

# Map
TARGET_FPS = 120
CHUNK_SIZE = 4
TILE_SIZE = 16


# Directories
GAME_FOLDER = path.dirname(__file__)
ASSETS_FOLDER = path.join(GAME_FOLDER, "assets")
MAP_FOLDER = path.join(ASSETS_FOLDER, "maps")
PLAYER_FOLDER = path.join(ASSETS_FOLDER, "player")

# Neural Network
ACTIVATION_FUNCTIONS = [relu, sigmoid, tanh]

#INITIAL_SIZES = (720, 1, 4)
INITIAL_SIZES = (2, 1, 1)
INPUTS = [[0, 0], [0, 1], [1, 0], [1, 1]]
NUMBER_OF_GENERATIONS = 1
PERCENTAGE_OF_INITIAL_CONNECTIONS = 0.2
GENERATION_SIZE = 1
TARGET_NUMBER_OF_SPECIES = 15
DISTANCE_THRESHOLD_STEP = 0.3
PERCENTAGE_OF_GENOMES_ALLOWED_TO_REPRODUCE = 0.2
ALLOW_RECURRENT_CONNECTIONS = True

MUTATE_WEIGHTS_CHANCE = 0.9
ADD_CONNECTION_CHANCE = 0.05
ADD_NODE_CHANCE = 0.03

RECURRENT_CONNECTION_CHANCE = 0.04
PLUS_OR_MINUS_20_PERCENT_CHANCE = 0.9
COMPLETELY_MUTATE_WEIGHT_CHANCE = 0.1
ENABLE_CONNECTION_CHANCE = 0.25
MUTATION_POWER = 2.5

EXPECTED_OUTPUTS = [0, 1, 1, 0]